server:
  port: 8000
  address: 0.0.0.0

spring:
  application:
    name: real-time-chat-app

  datasource:
#    url: jdbc:postgresql://localhost:5432/chatstorage
#    username: postgres
#    password:
#    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://160.191.50.248:5432/chatstorage
    username: postgres
    password: 20226100
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 100
      maxLifetime: 60000

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC+7

  data:
    elasticsearch:
      repositories:
        enabled: true
    redis:
      host: 160.191.50.248
      port: 6379

  elasticsearch:
    uris: http://160.191.50.248:9200
#    uris: http://localhost:9200
#    username: elastic
#    password: 20226100
    socket-timeout: 30s

  main:
    allow-bean-definition-overriding: true

  devtools:
    restart:
      exclude: logs/**

  cloud:
    aws:
      bucket-name: chatstoragebucket

  task:
    execution:
        pool:
            core-size: 10
            max-size: 20
            queue-capacity: 100

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: http://160.191.50.248:9092
    consumer:
      group-id: chat-group


logging:
#  file:
#    name: server/app/src/main/resources/logs/application.log
  level:
    org:
      springframework:
        security: DEBUG

        data:
          elasticsearch:
            core: DEBUG
            client:
              WIRE: trace


