server:
  port: 8000
  address: 0.0.0.0

spring:
  application:
    name: real-time-chat-app

#  datasource:
#    url: jdbc:postgresql://localhost:5432/chatstorage
#    username: postgres
#    password:
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://160.191.50.248:5432/chatstorage
    username: postgres
    password: 20226100
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC+7

  devtools:
    restart:
      exclude: logs/**

  cloud:
    aws:
      bucket-name: chatstoragebucket


logging:
#  file:
#    name: server/app/src/main/resources/logs/application.log
  level:
    org.springframework.security: DEBUG


