server:
  port: 8000

spring:
  application:
    name: real-time-chat-app

  datasource:
    url: jdbc:postgresql://postgres_db:5432/chatstorage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver  
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    restart:
      exclude: logs/**

logging:
    file:
      name: server/app/src/main/resources/logs/application.log
    level:
      org.springframework.security: DEBUG